### ISSUE TITLE
Perfunctory SSH keys collecting issue

### ISSUE THREAD

**Issue by C6H5-NO2** [hitsz-ldjam/git-playground#1]
"academic"

**Comment by VirFunc** [comment]
# Shut up and take my pub key
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC4Jf/PIRYaA1mbHMvNFWNMM7P/MSIMGPfbNQYfkn+uBLFQioGF3V0g/cqGyJJu830NN2PZMIgTL8IM0dUbwWD1+eJ6mhrLoeeQ/GVYZV0nm7YfbU9dXYZXgdFNfc8bXUR1klXeym//QC4zcZsL/rQ1Ce9vE4MimVkYGHwbmSLITEIuzWaaCi+iEPirKl1WJ47xYGvFsr2M4052tpGQEiKijQyk0FixOw5T0yoi8BbktUNVbCIB04gCZFpyLvUI/U9dcYgDwmSqwpYMwzQcl6UDO86tfAyUAfacO0KNzwzvxTnvBciN8F/7CIpVe1nRiDt+JTV9cHB2WYG7hTHqpMNvGjlYv6TJ9yJpVTZX/bhRNRvPtWslGDQFkvfyWw2NV5M7G7R75iXQR/7WkfMJDQMLmGgcCfUdQ5jFo6PeBMkudoxg2SG+AWEsiIzzUPU0Dnvc4PpTG9M6DG9BRCBvPsy2+6+78ohMKhGRJBJ1ronB6UF5u32uxAWI81M8FH0gdXk= Linux-Laptop
```

**Comment by 1371164370** [comment]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCha2OPixGoExAdgIhZkCzhaA+n0xIaPBltNnOASx8oJ8Fu13h6tv0vED9EURA+Hvc9P/41XKaFFnBNsX+g3XRx00PZ2DwiVHrSGzDiC2qHrxZrvoWUgHHPDb8YEg9M+zTcq2+w1NdlvsdwGRW1Pb2trgBRkkYMqUtUJ1iP5WSQUfm0Yi4gcpj0vMeuSpSma8k2YMb/JDnNjR+DkHnaO2zBEmW+90CXLkOMp+GnX1mbGhHWBOfwgviypYpOfyE1DoQKEFJ7uecu5tBIJHmWBvr1urmsrZJOmBELUyePvE9iY5VqX8vs/sxR7fZhncjTBFVZvS99PHRsnPhtFG6fy10X Project

**Comment by Lincyaw** [comment]
# This homework is so confusing
```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDHTb9INgim4gWm5zGqR4iWNc0LiTvRjZgAH1CQsRL3+O1/0TVhjREXjve+CJTKmhBBJPjJ1EmAwmGeDKiApU29MIALhYo2Odewt9a/wQFytEiwgBuxau6xod83wrNqic3oLoTS8Ydggdeg6XCUuGP6s1fkHIE2qjAWRSbbdNfrhp38b4mXo3eeHk5a56dsxVllZ9ccqxojL/Es/1XMG9CiMmLt17DrUvaAl0CDQCIIMcXIIwQJ6c+5FgtdwbPel20sPdqYAISnHP3Ry+Stkx0lemX0hsOhBf7gC5cwp3JX0EjeMxkHvrM6/iModaIRg1Y+YkNmoCVWvZTGVrQ3Ge0NMbTGvYMuc7scXhkYJvTpKX8+yhWKVgArNvhOztn73meFe++VjTQIDxM5acol1hbJ74aCmT5gSznS8KrcR5q4LhSVSpUbgF4rkisPCWNssMCl+v/BgLHEHA6DZiO/0ECge45Wo+k25GJM36Gmm3P3u7TBtq9N3fITyF3xkPcWcHU= llincyaw@llincyaw-TM1703
```

**Comment by maotouyingxia** [comment]
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCiTST3XovIPIF7RX7xPLGpRPf5qxj0RCI4ryiNbqTIobPQ3a/BMJsPFxLOMvIr56PtwDSErKhIVsu8MCJUJdjCA9/3wZYPHPG2l2xt1xOjVcBf4QM+KnGdVs8otPuSyzAqHJYeb99AeAi+y4M0yDSL+lSY2yrnd9VWS8uzHi/qNJHByuVzA+DxHzyzj+RnG69poJH0wUeckDXcZd9+v4kBJcIGhZMOWplgXI/tEo7S/KFnPuxEt4vwLE93UWnqb90TVa39oVeSzDcavgRc72NYCdhMuHhpLquI94l7079F7IPFAQOkZlzG7uVXQonG/saCgxoMcXIqQJH41IzXepRjf7/cI4dbNbsWvMzmIfu7HatdGclr/lEXRMYC5fDUPC+yG5PglX0XuNNVLwX1Izc4J4+NN0pZixQvTRYyIv9Cf+zp/DAiEjzQwoLukrvehATWzLVggIfY9NQ3Wcb41PzOIWQ41BaWd6/3dGfU6U1etcC+UT9t9Tt9PfZGW64pG6U= xiangxinxx@outlook.com

**Comment by C6H5-NO2** [comment]
Done
